-- Quiz seed SQL for Day 5 (docs/06.md) MongoDB import pipeline
DROP TABLE IF EXISTS quiz_questions;
CREATE TABLE quiz_questions (
  day INTEGER NOT NULL,
  question_no INTEGER NOT NULL,
  source_doc TEXT NOT NULL,
  topic TEXT NOT NULL,
  question TEXT NOT NULL,
  choice_1 TEXT NOT NULL,
  choice_2 TEXT NOT NULL,
  choice_3 TEXT NOT NULL,
  choice_4 TEXT NOT NULL,
  answer INTEGER NOT NULL,
  explanation TEXT NOT NULL,
  PRIMARY KEY (day, question_no)
);

INSERT INTO quiz_questions (day, question_no, source_doc, topic, question, choice_1, choice_2, choice_3, choice_4, answer, explanation) VALUES
(5, 1, '06', '반도체 KPI', '문서에서 반도체 산업의 핵심 KPI인 ASP(평균판매단가)와 가동률이 나타내는 것은?', '파이프라인 가치', '가격 사이클과 공급 여력', '운영 효율성', '반복매출 품질', 1, '문서 KPI 표에서 반도체의 핵심 KPI인 ASP(평균판매단가), 가동률의 의미는 가격 사이클과 공급 여력으로 설명됩니다.'),
(5, 2, '06', '유통·커머스 KPI', '문서에서 유통·커머스 산업의 핵심 KPI인 점포당 매출·객단가·GMV가 나타내는 것은?', '성장성과 유지율', '제품가-원가 차이', '운영 효율성', '수익성과 건전성', 2, '문서 KPI 표에서 유통·커머스의 핵심 KPI 의미는 운영 효율성으로 정의됩니다.'),
(5, 3, '06', '플랫폼·SaaS KPI', '문서에서 플랫폼·SaaS 산업의 핵심 KPI인 MAU·ARR·이탈률이 나타내는 것은?', '운영 효율성', '성장성과 유지율', '파이프라인 가치', '제품가-원가 차이', 1, '문서 KPI 표에서 플랫폼·SaaS의 MAU, ARR, 이탈률은 성장성과 유지율을 나타내는 지표로 설명됩니다.'),
(5, 4, '06', '금융·은행 KPI', '문서에서 금융·은행 산업의 핵심 KPI인 NIM(순이자마진)·ROE·대손충당금이 나타내는 것은?', '제품가-원가 차이', '성장성과 유지율', '운영 효율성', '수익성과 건전성', 3, '문서 KPI 표에서 금융·은행의 NIM, ROE, 대손충당금은 수익성과 건전성을 나타내는 지표입니다.'),
(5, 5, '06', '정유·화학 KPI', '문서에서 정유·화학 산업의 핵심 KPI인 크랙마진·정제마진·스프레드가 나타내는 것은?', '가격 사이클과 공급 여력', '제품가-원가 차이', '운영 효율성', '파이프라인 가치', 1, '문서 KPI 표에서 정유·화학의 크랙마진, 정제마진, 스프레드는 제품가-원가 차이를 나타내는 지표입니다.'),
(5, 6, '06', '바이오 KPI', '문서에서 바이오 산업의 핵심 KPI인 임상단계·R&D/매출 비율이 나타내는 것은?', '운영 효율성', '가격 사이클과 공급 여력', '파이프라인 가치', '제품가-원가 차이', 2, '문서 KPI 표에서 바이오의 임상단계와 R&D/매출 비율은 파이프라인 가치를 나타내는 지표로 설명됩니다.'),
(5, 7, '06', 'Peer Comparison 영업이익률', '문서에서 Peer Comparison 시 영업이익률을 비교하는 핵심 목적은?', '같은 시장에서 누가 빠르게 크는가', '같은 매출로 누가 더 많이 남기는가', '재무 건전성 차이를 파악하는가', '자본 효율성을 파악하는가', 1, '문서 비교 항목 표에서 영업이익률의 비교 이유는 같은 매출로 누가 더 많이 남기는가로 제시됩니다.'),
(5, 8, '06', 'Peer Comparison ROE', '문서에서 Peer Comparison 시 ROE를 비교하는 핵심 이유는?', '재무 건전성 차이 파악', '매출 성장 속도 파악', '자본 효율성 비교', '시장 평가 차이 파악', 2, '문서의 Peer Comparison 비교 항목 표에서 ROE의 비교 이유는 자본 효율성으로 설명됩니다.'),
(5, 9, '06', 'Peer Comparison 멀티플 주의점', '문서에서 Peer Comparison 시 멀티플 차이를 곧바로 저평가/고평가로 해석하면 안 되는 이유는?', '데이터 수집 방법이 다르기 때문', '비교 대상의 사업 구조가 실제로 다를 수 있기 때문', '환율 영향이 반영되지 않기 때문', '세금 체계가 나라마다 다르기 때문', 1, '문서에서 비교 대상의 사업 구조가 실제로 비슷한지 먼저 확인해야 멀티플 차이를 제대로 해석할 수 있다고 설명합니다.'),
(5, 10, '06', 'Peer Comparison 분석 흐름', '문서의 Peer Comparison 분석 흐름에서 저평가 기업의 할인 이유가 없을 때 결론은?', '리스크 요인 분석 후 관망', '포트폴리오에서 제외', '매수 기회 포착 → 비중 확대 검토', '추가 공시 확인 후 대기', 2, '문서 Peer Comparison 분석 흐름 다이어그램에서 할인 이유 없음 → 매수 기회 포착 → 비중 확대 검토로 연결됩니다.'),
(5, 11, '06', '공시 - 실적 발표', '문서에서 실적 발표 공시의 투자 관련 포인트로 제시된 것은?', '미래 매출 가시성 확보', '주주환원 신호', '컨센서스 대비 서프라이즈 여부', '기업 방향성 변화', 2, '문서 공시 종류 표에서 실적 발표의 투자 관련 포인트는 컨센서스 대비 서프라이즈 여부로 설명됩니다.'),
(5, 12, '06', '공시 - 유상증자', '문서에서 유상증자 공시의 투자 관련 포인트로 올바른 것은?', '주주환원 신호, 저평가 자신감', '단기 희석 부담 vs 장기 투자 재원', '컨센서스 대비 서프라이즈 여부', '기업 방향성 변화', 1, '문서 공시 종류 표에서 유상증자의 투자 관련 포인트는 단기 희석 부담 vs 장기 투자 재원으로 제시됩니다.'),
(5, 13, '06', '공시 - 자사주 매입', '문서에서 자사주 매입 공시가 나타내는 투자 신호는?', '미래 매출 가시성 확보', '단기 희석 부담', '컨센서스 대비 서프라이즈', '주주환원 신호, 저평가 자신감', 3, '문서 공시 종류 표에서 자사주 매입의 투자 관련 포인트는 주주환원 신호, 저평가 자신감으로 설명됩니다.'),
(5, 14, '06', '공시 - 대규모 수주', '문서에서 대규모 수주 공시의 투자 관련 포인트는?', '기업 방향성 변화', '미래 매출 가시성 확보', '단기 희석 부담', '주주환원 신호', 1, '문서 공시 종류 표에서 대규모 수주의 투자 관련 포인트는 미래 매출 가시성 확보로 제시됩니다.'),
(5, 15, '06', '공시 - 경영권 변경', '문서에서 경영권 변경 공시의 투자 관련 포인트는?', '컨센서스 대비 서프라이즈 여부', '주주환원 신호', '기업 방향성 변화', '미래 매출 가시성 확보', 2, '문서 공시 종류 표에서 경영권 변경의 투자 관련 포인트는 기업 방향성 변화로 설명됩니다.'),
(5, 16, '06', '다차원 분석 - 안정성', '문서에서 Peer Comparison 안정성(Stability) 축의 대표 지표로 제시된 것은?', '자산회전율, 재고회전율, 운전자본 회전', '부채비율, 유동비율, 순차입금', '변동성, 최대낙폭(MDD), 베타', '매출 성장률, EPS 성장률', 1, '문서 다차원 분석 축 표에서 안정성의 대표 지표는 부채비율, 유동비율, 순차입금입니다.'),
(5, 17, '06', '다차원 분석 - 효율성', '문서에서 Peer Comparison 효율성(Efficiency) 축의 대표 지표로 제시된 것은?', '변동성, 최대낙폭(MDD), 베타', 'PER, PBR, PSR, EV/EBITDA', '자산회전율, 재고회전율, 운전자본 회전', '부채비율, 유동비율', 2, '문서 다차원 분석 축 표에서 효율성의 대표 지표는 자산회전율, 재고회전율, 운전자본 회전입니다.'),
(5, 18, '06', '다차원 분석 - 리스크', '문서에서 Peer Comparison 리스크(Risk) 축의 대표 지표는?', '매출 성장률, EPS 성장률', '변동성, 최대낙폭(MDD), 베타', '자산회전율, 재고회전율', 'PER, PBR, PSR', 1, '문서 다차원 분석 축 표에서 리스크의 대표 지표는 변동성, 최대낙폭(MDD), 베타입니다.'),
(5, 19, '06', '다차원 분석 - 모멘텀', '문서에서 모멘텀(Momentum) 축의 대표 지표로 제시된 것은?', '변동성, MDD, 베타', 'HBM 비중, NIM, ARR', '1개월/3개월/1년 수익률, 52주 고점 대비 낙폭', '자산회전율, 재고회전율', 2, '문서 다차원 분석 축 표에서 모멘텀의 대표 지표는 1개월/3개월/1년 수익률, 52주 고점 대비 낙폭입니다.'),
(5, 20, '06', 'Peer 점수화 - higher_is_better', '문서의 Peer 점수화 코드에서 higher_is_better 목록에 포함되는 지표는?', 'debt_to_equity (부채비율)', 'trailing_pe (PER)', 'volatility_1y (연간 변동성)', 'roe (자기자본이익률)', 3, '문서 Peer 점수화 코드에서 higher_is_better 목록에는 revenue_growth, gross_margin, operating_margin, net_margin, roe, roa, current_ratio, return_1y가 포함됩니다.'),
(5, 21, '06', 'Peer 점수화 - lower_is_better', '문서의 Peer 점수화 코드에서 lower_is_better 목록에 포함되는 지표는?', 'revenue_growth (매출 성장률)', 'current_ratio (유동비율)', 'ev_to_ebitda (EV/EBITDA)', 'return_1y (1년 수익률)', 2, '문서 Peer 점수화 코드에서 lower_is_better 목록에는 debt_to_equity, trailing_pe, forward_pe, price_to_book, price_to_sales, ev_to_ebitda, volatility_1y가 포함됩니다.'),
(5, 22, '06', 'score_groups - growth_score', '문서에서 growth_score 그룹을 구성하는 지표는?', 'operating_margin_score, net_margin_score', 'revenue_growth_score', 'debt_to_equity_score, current_ratio_score', 'return_1y_score', 1, '문서 score_groups 정의에서 growth_score는 revenue_growth_score 하나로 구성됩니다.'),
(5, 23, '06', 'score_groups - stability_score', '문서에서 stability_score 그룹을 구성하는 지표로 맞는 것은?', 'gross_margin_score, operating_margin_score', 'trailing_pe_score, forward_pe_score', 'debt_to_equity_score, current_ratio_score', 'volatility_1y_score', 2, '문서 score_groups 정의에서 stability_score는 debt_to_equity_score와 current_ratio_score로 구성됩니다.'),
(5, 24, '06', '표준 산출물 - 점수화 파일', '문서의 Peer Comparison 고도화 실습에서 점수화 결과를 저장하는 표준 산출물 파일명은?', 'peer_raw_metrics.csv', 'peer_comparison_dataset.csv', 'peer_score_table.csv', 'peer_comparison_dashboard.png', 2, '문서에서 표준 산출물로 peer_raw_metrics.csv, peer_comparison_dataset.csv, peer_score_table.csv, peer_comparison_dashboard.png, peer_comparison_report.md가 제시되며, 점수화 결과는 peer_score_table.csv에 저장됩니다.'),
(5, 25, '06', 'peer-advanced API', '문서에서 다차원 Peer 비교 데이터와 차트를 반환하는 고도화 API 엔드포인트와 메서드는?', 'GET /api/industry/peer-advanced', 'POST /api/industry/peer-advanced', 'PUT /api/industry/peer-scores', 'GET /api/industry/peer-report', 1, '문서 API 설계 표에서 /api/industry/peer-advanced는 다차원 Peer 비교 데이터와 차트를 반환하는 POST 엔드포인트로 정의되어 있습니다.'),
(5, 26, '06', 'peer-report API 역할', '문서에서 /api/industry/peer-report API의 역할은?', '다차원 Peer 비교 데이터와 차트 반환', '성장·수익·안정·밸류·모멘텀 점수 계산', '산업별 KPI 입력/저장/점수화', 'Markdown/PDF용 분석 요약 생성', 3, '문서 API 설계 표에서 /api/industry/peer-report의 역할은 Markdown/PDF용 분석 요약 생성으로 설명됩니다.'),
(5, 27, '06', '화면 탭 구성', '문서의 Peer Comparison 화면 탭 구성에서 업종 특화 KPI 입력 및 점수화 탭은 몇 번인가?', '4번 탭', '5번 탭', '6번 탭', '7번 탭', 2, '문서 화면 탭 구성에서 6번 탭이 Industry KPI: 업종 특화 KPI 입력 및 점수화로 정의됩니다.'),
(5, 28, '06', '섹터 비교 API - XLV', '문서의 섹터 비교 API 기본 티커 목록에서 XLV가 대표하는 섹터는?', '에너지', '금융', '헬스케어', 'IT', 2, '문서 섹터 비교 API 티커 표에서 XLV는 헬스케어 섹터 ETF로 명시되어 있습니다.'),
(5, 29, '06', '포터 5 Forces API 차트', '문서에서 포터 5 Forces API 응답으로 반환되는 차트 타입은?', '막대 차트', '히트맵', '파이 차트', '레이더(거미줄) 차트', 3, '문서에서 포터 5 Forces API가 반환하는 차트는 5개 축의 레이더(거미줄) 차트로 산업 매력도를 한눈에 파악할 수 있다고 설명합니다.'),
(5, 30, '06', '수명주기 API stage', '문서의 수명주기 분석 API에서 stage 파라미터로 사용할 수 없는 값은?', '도입기', '성장기', '전환기', '성숙기', 2, '문서에서 수명주기 API의 stage는 도입기, 성장기, 성숙기, 쇠퇴기 중 하나로 정의됩니다. 전환기는 유효한 값이 아닙니다.');
