-- Quiz seed SQL for MongoDB import pipeline
DROP TABLE IF EXISTS quiz_questions;
CREATE TABLE quiz_questions (
  day INTEGER NOT NULL,
  question_no INTEGER NOT NULL,
  source_doc TEXT NOT NULL,
  topic TEXT NOT NULL,
  question TEXT NOT NULL,
  choice_1 TEXT NOT NULL,
  choice_2 TEXT NOT NULL,
  choice_3 TEXT NOT NULL,
  choice_4 TEXT NOT NULL,
  answer INTEGER NOT NULL,
  explanation TEXT NOT NULL,
  PRIMARY KEY (day, question_no)
);

INSERT INTO quiz_questions (day, question_no, source_doc, topic, question, choice_1, choice_2, choice_3, choice_4, answer, explanation) VALUES (1, 1, '01', '법적 주체', '법인이 자연인과 구별되는 핵심 특징으로 가장 적절한 것은?', '출생으로 성립한다', '법이 권리·의무 능력을 부여한 인위적 존재다', '세금을 내지 않는다', '해산해도 권리능력이 유지된다', 1, '법인은 설립 등기를 통해 성립하며, 법이 권리·의무의 주체성을 부여한 인위적 존재입니다.');
INSERT INTO quiz_questions (day, question_no, source_doc, topic, question, choice_1, choice_2, choice_3, choice_4, answer, explanation) VALUES (1, 2, '01', '사업자 형태', '개인사업자와 법인사업자의 비교로 옳은 것은?', '개인사업자는 대표자 급여를 비용 처리할 수 있다', '법인사업자는 무한책임이 원칙이다', '법인사업자는 주식 발행 등 외부 투자 유치가 상대적으로 용이하다', '개인사업자는 법인세를 낸다', 2, '법인사업자는 별도 법인격을 바탕으로 지분 구조 설계와 외부 투자 유치가 상대적으로 유리합니다.');
INSERT INTO quiz_questions (day, question_no, source_doc, topic, question, choice_1, choice_2, choice_3, choice_4, answer, explanation) VALUES (1, 3, '01', '책임 구조', '유한책임의 의미로 가장 적절한 것은?', '사업채무를 국가가 모두 대신 갚아준다', '출자액 한도 내에서만 책임을 부담한다', '대표이사가 모든 채무를 개인 재산으로 갚는다', '모든 주주는 무한책임을 진다', 1, '유한책임은 투자자가 출자한 금액 범위 내에서만 손실을 부담하는 구조입니다.');
INSERT INTO quiz_questions (day, question_no, source_doc, topic, question, choice_1, choice_2, choice_3, choice_4, answer, explanation) VALUES (1, 4, '01', '회사 형태', '상법상 회사 형태 중 실제로 가장 보편적으로 사용되는 형태는?', '합명회사', '합자회사', '유한회사', '주식회사', 3, '문서에서는 주식회사가 공개·상장 및 자본조달 측면에서 가장 보편적 형태로 제시됩니다.');
INSERT INTO quiz_questions (day, question_no, source_doc, topic, question, choice_1, choice_2, choice_3, choice_4, answer, explanation) VALUES (1, 5, '01', '주식회사 구조', '주식회사의 최고 의사결정 기관은?', '대표이사', '이사회', '주주총회', '감사', 2, '주주총회가 이사 선임, 정관 변경 등 핵심 사항을 결의하는 최고 의사결정 기관입니다.');
INSERT INTO quiz_questions (day, question_no, source_doc, topic, question, choice_1, choice_2, choice_3, choice_4, answer, explanation) VALUES (1, 6, '01', '주식 개념', '보통주에 대한 설명으로 가장 적절한 것은?', '의결권이 없다', '배당을 절대 받을 수 없다', '일반적으로 1주 1의결권을 가진다', '시가가 항상 액면가와 같다', 2, '문서 기준 보통주는 의결권이 있고 일반적으로 1주당 1표를 행사합니다.');
INSERT INTO quiz_questions (day, question_no, source_doc, topic, question, choice_1, choice_2, choice_3, choice_4, answer, explanation) VALUES (1, 7, '01', '소득세', '소득세(개인)와 법인세(법인)의 비교로 옳은 것은?', '소득세 최고세율이 법인세 최고세율보다 낮다', '법인세는 누진구조가 없다', '소득세는 누진세율 구조를 갖고 최고세율이 상대적으로 높다', '법인세는 지방소득세가 없다', 2, '문서에서 소득세는 6~45%, 법인세는 9~24%로 제시되어 개인 소득세 누진이 더 가파릅니다.');
INSERT INTO quiz_questions (day, question_no, source_doc, topic, question, choice_1, choice_2, choice_3, choice_4, answer, explanation) VALUES (1, 8, '01', '부가가치세', '부가가치세(VAT)에 대한 설명으로 옳은 것은?', '세율은 5%가 기본이다', '납부세액은 매출세액-매입세액으로 계산한다', '지방세만 해당된다', '직접세에 해당한다', 1, '문서에서는 부가가치세 기본세율 10%, 납부액은 매출세액에서 매입세액을 차감하는 구조로 설명합니다.');
INSERT INTO quiz_questions (day, question_no, source_doc, topic, question, choice_1, choice_2, choice_3, choice_4, answer, explanation) VALUES (1, 9, '01', '원천징수', '금융소득(이자·배당)의 기본 원천징수 세율로 문서에 제시된 값은?', '3.3%', '10.0%', '15.4%', '22.0%', 2, '이자·배당소득은 14% + 지방소득세 1.4%로 총 15.4% 원천징수로 제시됩니다.');
INSERT INTO quiz_questions (day, question_no, source_doc, topic, question, choice_1, choice_2, choice_3, choice_4, answer, explanation) VALUES (1, 10, '01', '직접세/간접세', '직접세에 해당하는 항목은?', '부가가치세', '주세', '소득세', '담배소비세', 2, '소득세는 납세자와 담세자가 동일한 직접세로 분류됩니다.');
INSERT INTO quiz_questions (day, question_no, source_doc, topic, question, choice_1, choice_2, choice_3, choice_4, answer, explanation) VALUES (1, 11, '01', '간접세', '간접세의 일반적 특징으로 가장 적절한 것은?', '누진세만 가능하다', '납세자와 담세자가 동일하다', '판매자가 납부하지만 소비자가 실질 부담할 수 있다', '지방정부만 부과할 수 있다', 2, '부가가치세처럼 판매자가 신고·납부하나 최종 부담은 소비자에게 전가되는 구조가 대표적입니다.');
INSERT INTO quiz_questions (day, question_no, source_doc, topic, question, choice_1, choice_2, choice_3, choice_4, answer, explanation) VALUES (1, 12, '01', '금융소득 종합과세', '연간 금융소득(이자+배당)이 얼마를 초과하면 종합소득에 합산 과세되는가?', '1,000만원', '2,000만원', '3,000만원', '5,000만원', 1, '문서에는 금융소득 합계 2,000만원 초과 시 종합과세로 설명되어 있습니다.');
INSERT INTO quiz_questions (day, question_no, source_doc, topic, question, choice_1, choice_2, choice_3, choice_4, answer, explanation) VALUES (1, 13, '01', '지방소득세', '지방소득세에 대한 설명으로 옳은 것은?', '소득세·법인세와 무관하다', '소득세·법인세 산출세액의 10%를 별도로 납부한다', '국세청이 아닌 거래소에 납부한다', '법인에게만 부과된다', 1, '문서에서는 지방소득세가 소득세·법인세 산출세액의 10%로 제시됩니다.');
INSERT INTO quiz_questions (day, question_no, source_doc, topic, question, choice_1, choice_2, choice_3, choice_4, answer, explanation) VALUES (1, 14, '01', '금융소비자보호법', '금융소비자보호법의 핵심 체계로 문서에서 제시한 것은?', '3대 판매 원칙', '6대 판매 원칙', '10대 내부통제 원칙', '위법계약 자동 무효', 1, '문서에서는 금소법 핵심 체계로 6대 판매원칙과 소비자 권리를 강조합니다.');
INSERT INTO quiz_questions (day, question_no, source_doc, topic, question, choice_1, choice_2, choice_3, choice_4, answer, explanation) VALUES (1, 15, '01', '예금자보호', '예금자보호법 관련 설명으로 옳은 것은?', '주식·펀드도 동일하게 전액 보호된다', '같은 금융기관 내 계좌는 1인당 5,000만원 한도로 합산 보호된다', '법인은 보호 대상에서 제외된다', '외화예금은 항상 전액 보호된다', 1, '문서에서는 1인당 5,000만원 한도, 동일 금융기관 내 합산 보호 원칙을 설명합니다.');
INSERT INTO quiz_questions (day, question_no, source_doc, topic, question, choice_1, choice_2, choice_3, choice_4, answer, explanation) VALUES (1, 16, '02', '업종/업태', '업종과 업태의 차이를 가장 잘 설명한 것은?', '업종=어떻게 팔아, 업태=무엇을 팔아', '업종=무엇을 팔아, 업태=어떻게 팔아', '둘은 완전히 동일하다', '업종은 세무와 무관하다', 1, '문서에서 업종은 재화·서비스 종류, 업태는 영업·유통 방식으로 구분합니다.');
INSERT INTO quiz_questions (day, question_no, source_doc, topic, question, choice_1, choice_2, choice_3, choice_4, answer, explanation) VALUES (1, 17, '02', '산업 분류', 'GICS에 대한 설명으로 가장 적절한 것은?', '한국 통계청이 만든 분류다', '글로벌 ETF·지수 분석에 쓰이는 표준 산업 분류다', '세금 신고 전용 분류다', '2단계 구조만 가진다', 1, 'GICS는 MSCI와 S&P가 만든 글로벌 산업 분류 체계로 포트폴리오 분석에 널리 활용됩니다.');
INSERT INTO quiz_questions (day, question_no, source_doc, topic, question, choice_1, choice_2, choice_3, choice_4, answer, explanation) VALUES (1, 18, '02', '가치사슬', '가치사슬에서 소비자와 가장 가까운 단계는?', '업스트림', '미드스트림', '다운스트림', '백오피스', 2, '다운스트림은 유통·소매·서비스 등 최종 소비자 접점에 가까운 단계입니다.');
INSERT INTO quiz_questions (day, question_no, source_doc, topic, question, choice_1, choice_2, choice_3, choice_4, answer, explanation) VALUES (1, 19, '02', '경기 사이클', '경기 확장기(Expansion)의 특징으로 문서에 제시된 것은?', '실업 급등, GDP 감소', '소비·투자 증가와 물가 상승', '금리 급인하', '필수소비재만 강세', 1, '확장기는 소비·투자 증가, 성장 가속과 함께 에너지·소재·IT 등이 강세로 제시됩니다.');
INSERT INTO quiz_questions (day, question_no, source_doc, topic, question, choice_1, choice_2, choice_3, choice_4, answer, explanation) VALUES (1, 20, '02', '경기 침체', '경기 침체기(Recession)에서 상대적 강세 섹터로 제시된 것은?', '에너지·산업재', '금융·부동산', '필수소비재·채권·금', '경기소비재', 2, '문서에서는 침체기에 필수소비재, 금, 국채 같은 방어적 자산이 강세라고 설명합니다.');
INSERT INTO quiz_questions (day, question_no, source_doc, topic, question, choice_1, choice_2, choice_3, choice_4, answer, explanation) VALUES (1, 21, '02', '핵심 지표', '거시지표와 설명의 연결이 옳은 것은?', 'CPI: 노동시장', '실업률: 인플레이션 수준', 'GDP 성장률: 경제 규모 성장 속도', '환율: 기업 내부 회계기준', 2, 'GDP 성장률은 경제 규모 성장 속도를 나타내는 대표 거시지표입니다.');
INSERT INTO quiz_questions (day, question_no, source_doc, topic, question, choice_1, choice_2, choice_3, choice_4, answer, explanation) VALUES (1, 22, '02', '기준금리/시장금리', '다음 중 시장금리에 해당하는 것은?', '한국은행 기준금리', '연준 정책금리 목표범위', '국채 10년물 금리', '법정 최고금리', 2, '국채 10년물 금리처럼 시장 수요·공급으로 형성되는 금리가 시장금리입니다.');
INSERT INTO quiz_questions (day, question_no, source_doc, topic, question, choice_1, choice_2, choice_3, choice_4, answer, explanation) VALUES (1, 23, '02', '금리 구조', '문서의 금리 구조 설명에서 단기 시장금리 예시는?', '국고채 30년', 'CD금리(91일)', '회사채 영구채', '우선주 배당수익률', 1, 'CD금리(91일), 콜금리 등이 단기 시장금리 예시로 제시됩니다.');
INSERT INTO quiz_questions (day, question_no, source_doc, topic, question, choice_1, choice_2, choice_3, choice_4, answer, explanation) VALUES (1, 24, '02', '금리-주가 관계', '일반적으로 금리 상승 시 주가에 하방 압력이 커지는 이유로 옳지 않은 것은?', '기업 차입비용 증가', '미래이익 할인율 상승', '채권의 상대적 매력 증가', '모든 기업의 매출이 즉시 증가', 3, '금리 상승은 보통 자금조달 부담을 키워 주가에 부담이며, 매출 즉시 증가가 일반적 결과는 아닙니다.');
INSERT INTO quiz_questions (day, question_no, source_doc, topic, question, choice_1, choice_2, choice_3, choice_4, answer, explanation) VALUES (1, 25, '02', '금리-채권 관계', '채권 가격과 금리의 관계로 가장 적절한 것은?', '같은 방향으로 움직인다', '금리와 무관하다', '금리 상승 시 기존 채권 가격은 하락하는 경향이 있다', '쿠폰이 고정이면 가격도 항상 고정된다', 2, '금리 상승 시 기존 저쿠폰 채권 매력이 낮아져 채권 가격이 하락하는 역관계가 일반적입니다.');
INSERT INTO quiz_questions (day, question_no, source_doc, topic, question, choice_1, choice_2, choice_3, choice_4, answer, explanation) VALUES (1, 26, '02', '통화정책 기관', '한국은행 금통위에 대한 설명으로 문서와 일치하는 것은?', '연 12회 정기회의', '총재 포함 7명 구성, 연 8회 정기회의', '정책금리 결정 권한이 없다', '오직 환율만 보고 결정한다', 1, '문서에서 금통위는 총재 포함 7명, 연 8회 정기회의로 기준금리를 결정한다고 설명합니다.');
INSERT INTO quiz_questions (day, question_no, source_doc, topic, question, choice_1, choice_2, choice_3, choice_4, answer, explanation) VALUES (1, 27, '02', 'FOMC', 'FOMC의 정책 신호 중 ''매파(Hawkish)''가 의미하는 것은?', '금리 인하 선호', '경기 부양 우선', '금리 인상 선호 및 인플레이션 억제 우선', '양적완화 무조건 확대', 2, '매파적 스탠스는 물가 안정 우선, 상대적으로 긴축적 금리 정책 선호를 의미합니다.');
INSERT INTO quiz_questions (day, question_no, source_doc, topic, question, choice_1, choice_2, choice_3, choice_4, answer, explanation) VALUES (1, 28, '02', '데이터 소스', '국내 기준금리·국고채·CD금리 데이터를 공식적으로 조회할 때 문서에서 우선 권장한 출처는?', '네이버 금융 기사', '한국은행 ECOS', '개인 블로그', '임의 커뮤니티 엑셀 파일', 1, '문서에서는 국내 금리 데이터의 1차 신뢰 원천으로 한국은행 ECOS를 강조합니다.');
INSERT INTO quiz_questions (day, question_no, source_doc, topic, question, choice_1, choice_2, choice_3, choice_4, answer, explanation) VALUES (1, 29, '02', 'FRED 시리즈', '문서에서 금리 실습 시 자주 사용하는 FRED 시리즈로 언급된 것은?', 'FEDFUNDS, DGS2, DGS10', 'BTCUSD, ETHUSD, DOGEUSD', 'KOSPI, KOSDAQ, KRX300', 'GDPDEF, CPIAUCSL만 단독 사용', 0, '문서에 FEDFUNDS, DGS2, DGS10, DGS30, T10Y2Y 등이 대표 시리즈로 제시됩니다.');
INSERT INTO quiz_questions (day, question_no, source_doc, topic, question, choice_1, choice_2, choice_3, choice_4, answer, explanation) VALUES (1, 30, '02', '스프레드 해석', '장단기 금리 스프레드를 볼 때 주의할 점으로 가장 적절한 것은?', '장단기 금리 차이는 의미가 없다', '정책금리와 시장금리를 항상 동일 지표로 취급한다', '국가·통화·지표 정의 차이를 확인하고 방향성과 함께 해석한다', '스프레드가 0이면 무조건 강세장이다', 2, '문서에서는 지표 정의(정책/시장금리), 국가 차이를 확인하고 스프레드의 방향성을 함께 해석하라고 설명합니다.');
